spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/finaldb
    username: admin
    password: admin

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:9092

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    connection-timeout: 10s
    socket-timeout: 30s


  logging:
    level:
      root: DEBUG

